### ISSUE TITLE
Using the same target dataset for both training and testing in Office31

### ISSUE THREAD

**Issue by bardisafa** [TencentYoutuResearch/ActiveLearning-SDM#1]
Hi, I realized that you are testing the model on the same target dataset that was used during trainng and active sampling ('tr_or_te' doesn't exist in the filename). Here:
https://github.com/TencentYoutuResearch/ActiveLearning-SDM/blob/0ee700e59451131536b7509ff3d4b266835ac01b/run.py#L29-L32
Could you explain why you did that? Thanks

**Comment by lyxok1** [comment]
Hi, we train and test the model in the same target dataset to follow a standard setting the field of Domain Adaptation, you can refer to some previous work like [TQS](https://github.com/thuml/Transferable-Query-Selection) or [CDAN](https://github.com/thuml/CDAN/blob/master/pytorch/train_image.py), these classic work also take target domain as available data without label during training.
